POST http://localhost:5000/register
Content-Type: application/json

{
    "email":"nghia6@gmail.com",
    "password":"123456789"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"nghia6@gmail.com",
    "password":"123456789"
}


###
GET http://localhost:5000/account
Content-Type: application/json

###
GET http://localhost:5000/checklogin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjY2NzgwNTg0fQ.czaiZ6jHgIUhk4ioAM_MGB0_2KJ2ykuvDB7IPqt7BWg


###
GET http://localhost:5000/account/1
Content-Type: application/json

###
POST http://localhost:5000/todo/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjY2NzgwNTg0fQ.czaiZ6jHgIUhk4ioAM_MGB0_2KJ2ykuvDB7IPqt7BWg

{
    "title":"test123",
    "desc":"test",
    "is_done":false
}

###
GET http://localhost:5000/todo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjY2NzgwNTg0fQ.czaiZ6jHgIUhk4ioAM_MGB0_2KJ2ykuvDB7IPqt7BWg

###
GET http://localhost:5000/todo/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjY2NzgwNTg0fQ.czaiZ6jHgIUhk4ioAM_MGB0_2KJ2ykuvDB7IPqt7BWg

###
PUT http://localhost:5000/todo/update/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjY2NzgwNTg0fQ.czaiZ6jHgIUhk4ioAM_MGB0_2KJ2ykuvDB7IPqt7BWg

{
    "title":"test1",
    "desc":"test"
}

###
DELETE  http://localhost:5000/todo/delete/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjY2NzgwNTg0fQ.czaiZ6jHgIUhk4ioAM_MGB0_2KJ2ykuvDB7IPqt7BWg


###
POST   http://localhost:5000/todo/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjY2NzgwNTg0fQ.czaiZ6jHgIUhk4ioAM_MGB0_2KJ2ykuvDB7IPqt7BWg

{
    "title":"test2",
    "is_done":false
}

###
POST   http://localhost:5000/todo/updateStatus/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjY2NzgwNTg0fQ.czaiZ6jHgIUhk4ioAM_MGB0_2KJ2ykuvDB7IPqt7BWg

{
    "is_done":false
}